---
title: C6320 | Microsoft-Dokumentation
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 1d37a8d33f756372cd0448e94cf9f6d5e2408cf1
ms.sourcegitcommit: 6cfffa72af599a9d667249caaaa411bb28ea69fd
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 09/02/2020
ms.locfileid: "77273420"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Warnung C6320: Der Ausnahmefilterausdruck ist die EXCEPTION_EXECUTE_HANDLER-Konstante. Hierdurch werden möglicherweise Ausnahmen maskiert, für die keine Behandlung vorgesehen war.  
  
 Diese Warnung gibt den Nebeneffekt der Verwendung EXCEPTION_EXECUTE_HANDLER Konstanten in __except Block an. In diesem Fall wird die-Anweisung im \_ _except-Block immer ausgeführt, um die Ausnahme zu behandeln, einschließlich Ausnahmen, die Sie nicht in einer bestimmten Funktion behandeln wollten. Es wird empfohlen, dass Sie die Ausnahme vor der Behandlung überprüfen.  
  
## <a name="example"></a>Beispiel  
 Mit dem folgenden Code wird diese Warnung generiert, da der __except-Block versucht, Ausnahmen aller Typen zu behandeln:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Um diese Warnung zu korrigieren, verwenden Sie, `GetExceptionCode` um eine bestimmte Ausnahme zu überprüfen, bevor Sie Sie behandeln, wie im folgenden Code gezeigt:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Weitere Informationen  
 [try-except-Anweisung](https://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)
